[mypy]
# Specify the target platform details in config, so your developers are
# free to run mypy on Windows, Linux, or macOS and get consistent
# results.
python_version = 3.10
platform=linux

show_column_numbers=True

follow_imports=normal

# suppress errors about unsatisfied imports
ignore_missing_imports=True

# be strict
warn_return_any = True
warn_unused_configs = True
strict_optional=True
warn_no_return=True
warn_redundant_casts=True
warn_unused_ignores=True

# The following are off by default.  Flip them on if you feel
# adventurous.
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True

# No incremental mode
cache_dir=/dev/null

namespace_packages = True
explicit_package_bases = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-numpy]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy.plugins.numpy.*]
follow_imports = skip

[mypy.plugins.pandas.*]
follow_imports = skip
